### ISSUE TITLE
Running app.py

### ISSUE THREAD

**Issue by Wilmerben** [dnuka/banda#13]
After installing the requirements and running app.py, I get this: 

``` ssh

raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: 
Unable to find a  matching set of capabilities
```

I'm using windows 10 and running banda in vagrant, python3

**Comment by dnuka** [comment]
Hi @Wilmerben 
Thanks for opening the issue. Will look into it :)

**Comment by dnuka** [comment]
@Wilmerben Hi :)
Just updated the repo. New changes resolve the above exception. Also, you may need to download the appropriate [geckodriver](https://github.com/mozilla/geckodriver/releases/tag/v0.24.0). Since you're on Windows, you may need to download the geckodriver for Windows and replace the default one.

Thanks!
